In [49]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [112]:
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2, output_size):
        super(MLP, self).__init__()
        # First hidden layer
        self.fc1 = nn.Linear(input_size, hidden_size1)
        # Second hidden layer
        self.fc2 = nn.Linear(hidden_size1, hidden_size2)
        # Output layer
        self.fc3 = nn.Linear(hidden_size2, output_size)

    def forward(self, x):
        # Apply ReLU activation function after each hidden layer
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        # Output layer does not have an activation function here
        # This can be changed depending on the problem
        x = self.fc3(x)
        return x

In [113]:
import pandas as pd
data = '../../data/Processed_Data/leakage_PCA_results.csv'
df = pd.read_csv(data)
df

Unnamed: 0          0          1          2          3          4  \
0            0  -7.421883  -0.819801   2.028855  -0.073532   0.386171   
1            1 -15.323043  -0.497512   0.746582  -0.572069  -0.293702   
2            2  -6.114105  -1.917797   1.015368  -0.520744   0.568313   
3            3  -9.479358  -0.598465   1.138944  -1.682208  -0.447917   
4            4  -0.860349   2.826234  -1.645340   0.110626  -0.705991   
5            5  22.702054  -6.145934  14.438932  -1.278658  -0.390812   
6            6 -11.670814  -0.705471   0.988405  -1.104385  -0.148293   
7            7  21.102197  13.969196  -3.822477  -4.349144  -1.024219   
8            8  15.629545 -13.089129  -8.578873   2.472203   6.806673   
9            9  -6.229331  -2.089063  -4.332429  -1.229604  -0.440454   
10          10   3.431775   6.817663  -1.207726  -4.715815   0.837907   
11          11   9.587894   1.207090  -2.264936  13.622634  -7.248427   
12          12 -11.105806  -0.690690   1.009000  -0.926850  -0.443512   
13          13  -4.248776   1.733678   0.485694   0.247546   2.544262   
14          14 -11.183567  -1.884338  -0.522220  -1.752500  -0.574741   
15          15   1.718855   1.492352   2.838616  -0.322816   0.013017   
16          16  -7.975433  -1.520955  -1.458573  -1.935671  -0.691189   
17          17  -5.468953  -0.583348  -0.439854  -0.073533  -0.139639   
18          18  -6.534239  -0.745070   0.607771   0.261827  -1.584215   
19          19  -5.087306  -2.636252  -1.119639  -1.791569  -0.235832   
20          20 -11.968966  -2.213473  -1.103760  -1.319124  -1.425346   
21          21  -2.735570   0.927926   0.386989  -0.975265  -0.444457   
22          22  -1.484109   0.146720   1.197566   1.196602   0.471961   
23          23  -6.616746  -0.305389   0.487327   1.617409  -0.680059   
24          24  12.186973   4.854992   3.579465   4.216707  10.398452   
25          25   7.191135   3.240463  -4.507807   0.223297   2.875809   
26          26  -1.253293   1.808940   1.522724   3.407527  -0.293880   
27          27 -10.172113  -1.786571   0.171307  -1.339912  -0.742774   
28          28   5.302718   2.802734   0.159990  -0.450291  -0.245387   
29          29  -1.557799   0.381880   0.048580  -0.040442  -0.933425   
30          30 -11.059352  -1.194506  -0.279714  -1.833771  -0.801584   
31          31  53.096971  -5.757169  -2.283804  -5.120463  -4.630952   
32          32  11.378909   4.388563   1.800247   5.210758   1.132559   
33          33  -7.778116  -1.417499  -1.085213   0.821231  -1.468319   

           5         6         7         8  ...        21        22        23  \
0   0.520307  0.428431  0.004742  0.261842  ...  1.935535 -0.154354 -0.073339   
1  -0.788136 -0.306839 -0.145643 -1.027761  ... -0.867788 -0.746950 -0.166749   
2  -1.013364 -0.736610 -1.026600  0.166252  ...  0.451643  2.639849  0.857328   
3  -0.852024  0.943453  0.974503 -1.150230  ... -0.745642 -1.616556  1.069615   
4   5.088344 -3.443486 -1.446917  5.202910  ... -0.063848 -0.490979  0.111466   
5   2.326675 -0.972968  1.078863 -0.844269  ... -0.198334  0.196434  0.163218   
6  -1.098986  0.169497 -0.337228 -0.911866  ...  0.172902 -0.408186 -0.610731   
7  -3.045905 -1.152868 -1.963143 -0.573966  ...  0.301473  0.123082 -0.029004   
8  -0.830775 -0.720848 -3.003660 -0.102748  ... -0.020110  0.071697  0.145143   
9   0.410175  1.297200  0.665759 -0.162798  ...  0.323802 -0.540623 -0.774510   
10 -2.076863  1.868966  1.812672 -1.241018  ... -0.491755  0.669588  0.147958   
11 -1.021219  3.439409  2.381423  0.412551  ... -0.183210  0.337137 -0.138257   
12 -1.052386 -0.712562 -0.628590 -0.913576  ... -0.644673 -0.083706 -0.095010   
13  3.434157 -0.100775  1.633819  0.884678  ...  0.030004  0.003568 -0.607129   
14 -0.477536  0.013819  0.153960 -0.001691  ... -0.433705 -0.114195  0.000402   
15 -1.155055  1.267257 -1.434224  7.540400  ... -0.219143  0.308285 -0.053393   
16 -0.996028  1.114716  0.768668  0.345843  ...  0.515466  1.119966  1.

In [114]:
input_size = 30    # 3 components
hidden_size1 = 50  # number of neurons in the first hidden layer
hidden_size2 = 50  # number of neurons in the second hidden layer
output_size = 2    # number of output classes: leakage/non leakage

# Create an instance of the MLP
mlp = MLP(input_size, hidden_size1, hidden_size2, output_size)

In [115]:
input_df = df.iloc[:, 1:df.shape[1]-1]
input_df

0          1          2          3          4         5         6  \
0   -7.421883  -0.819801   2.028855  -0.073532   0.386171  0.520307  0.428431   
1  -15.323043  -0.497512   0.746582  -0.572069  -0.293702 -0.788136 -0.306839   
2   -6.114105  -1.917797   1.015368  -0.520744   0.568313 -1.013364 -0.736610   
3   -9.479358  -0.598465   1.138944  -1.682208  -0.447917 -0.852024  0.943453   
4   -0.860349   2.826234  -1.645340   0.110626  -0.705991  5.088344 -3.443486   
5   22.702054  -6.145934  14.438932  -1.278658  -0.390812  2.326675 -0.972968   
6  -11.670814  -0.705471   0.988405  -1.104385  -0.148293 -1.098986  0.169497   
7   21.102197  13.969196  -3.822477  -4.349144  -1.024219 -3.045905 -1.152868   
8   15.629545 -13.089129  -8.578873   2.472203   6.806673 -0.830775 -0.720848   
9   -6.229331  -2.089063  -4.332429  -1.229604  -0.440454  0.410175  1.297200   
10   3.431775   6.817663  -1.207726  -4.715815   0.837907 -2.076863  1.868966   
11   9.587894   1.207090  -2.264936  13.622634  -7.248427 -1.021219  3.439409   
12 -11.105806  -0.690690   1.009000  -0.926850  -0.443512 -1.052386 -0.712562   
13  -4.248776   1.733678   0.485694   0.247546   2.544262  3.434157 -0.100775   
14 -11.183567  -1.884338  -0.522220  -1.752500  -0.574741 -0.477536  0.013819   
15   1.718855   1.492352   2.838616  -0.322816   0.013017 -1.155055  1.267257   
16  -7.975433  -1.520955  -1.458573  -1.935671  -0.691189 -0.996028  1.114716   
17  -5.468953  -0.583348  -0.439854  -0.073533  -0.139639 -0.117016  0.204708   
18  -6.534239  -0.745070   0.607771   0.261827  -1.584215 -0.927224 -0.950706   
19  -5.087306  -2.636252  -1.119639  -1.791569  -0.235832  0.115752  1.368380   
20 -11.968966  -2.213473  -1.103760  -1.319124  -1.425346 -0.929677 -0.009517   
21  -2.735570   0.927926   0.386989  -0.975265  -0.444457 -1.171031 -0.046046   
22  -1.484109   0.146720   1.197566   1.196602   0.471961 -0.713479 -0.203511   
23  -6.616746  -0.305389   0.487327   1.617409  -0.680059 -0.663018 -2.432457   
24  12.186973   4.854992   3.579465   4.216707  10.398452 -3.822214  3.901606   
25   7.191135   3.240463  -4.507807   0.223297   2.875809  7.173564 -3.202784   
26  -1.253293   1.808940   1.522724   3.407527  -0.293880 -0.992081 -3.029694   
27 -10.172113  -1.786571   0.171307  -1.339912  -0.742774 -0.563639 -0.085865   
28   5.302718   2.802734   0.159990  -0.450291  -0.245387  7.648816  7.325439   
29  -1.557799   0.381880   0.048580  -0.040442  -0.933425  0.940630 -0.144123   
30 -11.059352  -1.194506  -0.279714  -1.833771  -0.801584 -0.859738  0.947900   
31  53.096971  -5.757169  -2.283804  -5.120463  -4.630952 -1.587940  0.241458   
32  11.378909   4.388563   1.800247   5.210758   1.132559 -0.240005 -5.605376   
33  -7.778116  -1.417499  -1.085213   0.821231  -1.468319 -0.663081 -0.675204   

           7         8         9  ...        20        21        22        23  \
0   0.004742  0.261842 -0.063258  ...  0.631876  1.935535 -0.154354 -0.073339   
1  -0.145643 -1.027761 -0.776574  ... -0.346579 -0.867788 -0.746950 -0.166749   
2  -1.026600  0.166252  0.641319  ... -1.241336  0.451643  2.639849  0.857328   
3   0.974503 -1.150230  0.399990  ... -0.223303 -0.745642 -1.616556  1.069615   
4  -1.446917  5.202910  4.543827  ... -0.040899 -0.063848 -0.490979  0.111466   
5   1.078863 -0.844269 -1.373267  ...  0.561811 -0.198334  0.196434  0.163218   
6  -0.337228 -0.911866  0.323815  ...  0.046696  0.172902 -0.408186 -0.610731   
7  -1.963143 -0.573966 -0.955189  ...  0.676554  0.301473  0.123082 -0.029004   
8  -3.003660 -0.102748 -1.624297  ...  0.155284 -0.020110  0.071697  0.145143   
9   0.665759 -0.162798 -1.016849  ... -0.527296  0.323802 -0.540623 -0.774510   
10  1.812672 -1.241018 -1.222568  ... -0.286838 -0.491755  0.669588  0.147958   
11  2.381423  0.412551 -0.391773  ...  0.212414 -0.183210  0.337137 -0.138257   
12 -0.628590 -0.913576 -0.200381  ... -0.269699 -0.644673 -0.083706 -0.095010   
13  1.633819  0.884678  1.715205  ...  0.6

In [116]:
#converting input data to tensor
forward_pass_example = input_df.iloc[0]
forward_pass_example = torch.tensor(forward_pass_example.values, dtype=torch.float32)
type(forward_pass_example)

torch.Tensor

In [117]:
#forward pass example
#lowkey what do these output values mean because I didn't give it Y info yet ??
output = mlp(forward_pass_example)
print(output)

tensor([-0.1711,  0.2567], grad_fn=<AddBackward0>)


In [118]:
# Back propagation
import torch.optim as optim

In [119]:
import numpy as np
from sklearn.model_selection import train_test_split

X = df.iloc[:, 1:df.shape[1]-1]
y = np.where(df["Status"] == "Non leakage", 0, 1)

# Splitting the data into training and test sets by a 80:20 ratio
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [120]:
torch.tensor(y_test)

tensor([1, 1, 0, 1, 1, 0, 0])

In [121]:
# Putting in the dataset from PCA results
# Assuming inputs are of size 10 and there are 3 classes
X_train = torch.tensor(X_train.values, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long) #labels
X_test = torch.tensor(X_test.values, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.long) #labels

In [122]:
# Loss function
criterion = nn.CrossEntropyLoss()

# Optimizer (e.g., Stochastic Gradient Descent)
optimizer = optim.SGD(mlp.parameters(), lr=0.01)

In [123]:
# Training loop
for epoch in range(5):  # number of epochs
    for i in range(len(X_train)):
        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = mlp(X_train[i])

        # Compute the loss
        loss = criterion(outputs.unsqueeze(0), y_train[i].unsqueeze(0))

        # Backward pass
        loss.backward()

        # Update weights
        optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.6112395524978638
Epoch 2, Loss: 0.613912045955658
Epoch 3, Loss: 0.5947532653808594
Epoch 4, Loss: 0.5693315863609314
Epoch 5, Loss: 0.5221114158630371


In [124]:

#returns logit values
mlp(X_test)

tensor([[ 0.2186,  0.0239],
        [ 0.3284, -0.1497],
        [-0.1834,  0.4857],
        [ 0.2679, -0.2145],
        [ 0.0638,  0.0773],
        [ 0.0978,  0.0865],
        [ 0.0180,  0.3114]], grad_fn=<AddmmBackward0>)

In [125]:
mlp.eval()  # Set the model to evaluation mode
with torch.no_grad():
    # Apply softmax to get probabilities
    probabilities = F.softmax(mlp(X_test), dim=1)
print(probabilities)

tensor([[0.5485, 0.4515],
        [0.6173, 0.3827],
        [0.3387, 0.6613],
        [0.6183, 0.3817],
        [0.4966, 0.5034],
        [0.5028, 0.4972],
        [0.4272, 0.5728]])


In [126]:
predicted_labels = torch.argmax(probabilities, dim=1)
print(predicted_labels)

tensor([0, 0, 1, 0, 1, 0, 1])


In [127]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)
print(accuracy)

0.2857142857142857
